name: Publish
run-name: Publish library to GitHub Packages.
on:
  push:
    branches:
      - issue/publish_lib
      #- main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Run test
        run: ./gradlew :shared:jvmTest  --rerun-tasks --continue
      - name: Run Build & Publish
        uses: ./gradlew :shared:publish
