name: Publish
run-name: Publish library to GitHub Packages.
on:
  push:
    branches:
      - issue/publish_lib
#      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: wrapper
          cache-read-only: false
          cache-overwrite-existing: true
      - name: Publish
        run: ./gradlew clean :shared:publish
