name: Publish
run-name: Publish library to GitHub Packages.
on:
  push:
    branches:
      - issue/publish_lib
#      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Publish
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: "clean :shared:publish"
          gradle-version: wrapper
          cache-read-only: false
