name: Min CI (JVM test only)
run-name: "ID:${{ github.run_id }}), ref:${{ github.ref_name }}, sha:${{ github.sha }})"
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Run test
        run: ./gradlew :shared:jvmTest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "**/build/reports/tests/jvmTest/*.*"
