name: Min CI (JVM test only)
run-name: "#${{ github.run_number }}, ID:${{ github.run_id }}), ref:${{ github.ref_name }}, sha:${{ github.sha }}), @${{ github.actor }}"
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test
        run: ./gradlew :shared:jvmTest
