name: Min CI (JVM test only)
run-name: "ID:${{ github.run_id }}, SHA:${{ github.sha }})"
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Run test
        run: ./gradlew :shared:jvmTest  --rerun-tasks --continue
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        name: Upload test report
        with:
          name: "JVM test report ${{ github.run_id }} ${{ github.sha }}"
          path: shared/build/reports/tests/jvmTest
